//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.16 at 02:08:28 PM EDT 
//


package org.kitfox.stm.v1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="NumeroRue">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *               &lt;maxLength value="100"/>
 *               &lt;minLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="AdresseComplement" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *               &lt;maxLength value="100"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Ville">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *               &lt;maxLength value="50"/>
 *               &lt;minLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Province">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *               &lt;maxLength value="2"/>
 *               &lt;minLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="CodePostal">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *               &lt;maxLength value="6"/>
 *               &lt;pattern value="^([a-zA-Z]\d[a-zA-z]?\d[a-zA-Z]\d)$"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Courriel">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *               &lt;maxLength value="320"/>
 *               &lt;pattern value="^[\p{L}0-9!#$%&amp;'*+/=?^_`{|}~-]+(\.[\p{L}0-9!#$%&amp;'*+/=?^_`{|}~-]+)*@([\p{L}0-9]([\p{L}0-9-]*[\p{L}0-9])?\.)+[\p{L}0-9]([\p{L}0-9-]*[\p{L}0-9])?$"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Telephone">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *               &lt;maxLength value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Poste" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *               &lt;maxLength value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "numeroRue",
    "adresseComplement",
    "ville",
    "province",
    "codePostal",
    "courriel",
    "telephone",
    "poste"
})
public class Contact {

    @XmlElement(name = "NumeroRue", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String numeroRue;
    @XmlElement(name = "AdresseComplement")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String adresseComplement;
    @XmlElement(name = "Ville", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String ville;
    @XmlElement(name = "Province", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String province;
    @XmlElement(name = "CodePostal", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String codePostal;
    @XmlElement(name = "Courriel", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String courriel;
    @XmlElement(name = "Telephone", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String telephone;
    @XmlElement(name = "Poste")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String poste;

    /**
     * Gets the value of the numeroRue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumeroRue() {
        return numeroRue;
    }

    /**
     * Sets the value of the numeroRue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumeroRue(String value) {
        this.numeroRue = value;
    }

    /**
     * Gets the value of the adresseComplement property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdresseComplement() {
        return adresseComplement;
    }

    /**
     * Sets the value of the adresseComplement property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdresseComplement(String value) {
        this.adresseComplement = value;
    }

    /**
     * Gets the value of the ville property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVille() {
        return ville;
    }

    /**
     * Sets the value of the ville property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVille(String value) {
        this.ville = value;
    }

    /**
     * Gets the value of the province property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProvince() {
        return province;
    }

    /**
     * Sets the value of the province property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProvince(String value) {
        this.province = value;
    }

    /**
     * Gets the value of the codePostal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodePostal() {
        return codePostal;
    }

    /**
     * Sets the value of the codePostal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodePostal(String value) {
        this.codePostal = value;
    }

    /**
     * Gets the value of the courriel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCourriel() {
        return courriel;
    }

    /**
     * Sets the value of the courriel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCourriel(String value) {
        this.courriel = value;
    }

    /**
     * Gets the value of the telephone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * Sets the value of the telephone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTelephone(String value) {
        this.telephone = value;
    }

    /**
     * Gets the value of the poste property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPoste() {
        return poste;
    }

    /**
     * Sets the value of the poste property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPoste(String value) {
        this.poste = value;
    }

}
