//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.16 at 02:08:28 PM EDT 
//


package org.kitfox.stm.v1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="NoInstitution">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *               &lt;pattern value="^\d{6}$"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="NoSousInstitution" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *               &lt;pattern value="^\d{6}$"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="AnneeScolaire" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *               &lt;pattern value="^\d{4}-\d{4}$"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "noInstitution",
    "noSousInstitution",
    "anneeScolaire"
})
public class Institution {

    @XmlElement(name = "NoInstitution", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String noInstitution;
    @XmlElement(name = "NoSousInstitution")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String noSousInstitution;
    @XmlElement(name = "AnneeScolaire")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String anneeScolaire;

    /**
     * Gets the value of the noInstitution property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNoInstitution() {
        return noInstitution;
    }

    /**
     * Sets the value of the noInstitution property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNoInstitution(String value) {
        this.noInstitution = value;
    }

    /**
     * Gets the value of the noSousInstitution property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNoSousInstitution() {
        return noSousInstitution;
    }

    /**
     * Sets the value of the noSousInstitution property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNoSousInstitution(String value) {
        this.noSousInstitution = value;
    }

    /**
     * Gets the value of the anneeScolaire property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAnneeScolaire() {
        return anneeScolaire;
    }

    /**
     * Sets the value of the anneeScolaire property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAnneeScolaire(String value) {
        this.anneeScolaire = value;
    }

}
