//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.16 at 02:08:28 PM EDT 
//


package org.kitfox.stm.v1;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.kitfox.stm.v1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.kitfox.stm.v1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ReferencePreparationDemandeCarteEtudiant }
     * 
     */
    public ReferencePreparationDemandeCarteEtudiant createReferencePreparationDemandeCarteEtudiant() {
        return new ReferencePreparationDemandeCarteEtudiant();
    }

    /**
     * Create an instance of {@link Erreurs }
     * 
     */
    public Erreurs createErreurs() {
        return new Erreurs();
    }

    /**
     * Create an instance of {@link Erreur }
     * 
     */
    public Erreur createErreur() {
        return new Erreur();
    }

    /**
     * Create an instance of {@link PreparationDemandeCarteEtudiant }
     * 
     */
    public PreparationDemandeCarteEtudiant createPreparationDemandeCarteEtudiant() {
        return new PreparationDemandeCarteEtudiant();
    }

    /**
     * Create an instance of {@link Institution }
     * 
     */
    public Institution createInstitution() {
        return new Institution();
    }

    /**
     * Create an instance of {@link Etudiant }
     * 
     */
    public Etudiant createEtudiant() {
        return new Etudiant();
    }

    /**
     * Create an instance of {@link Tuteur }
     * 
     */
    public Tuteur createTuteur() {
        return new Tuteur();
    }

    /**
     * Create an instance of {@link Contact }
     * 
     */
    public Contact createContact() {
        return new Contact();
    }

}
