//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.17 at 12:22:59 PM EDT 
//


package org.kitfox.stm.msg;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Contenu" maxOccurs="2" minOccurs="2">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Langue" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Date" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Texte" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Preambule" maxOccurs="2" minOccurs="2">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Langue" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Date" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Texte" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "contenu",
    "preambule"
})
@XmlRootElement(name = "MessageLegal")
public class MessageLegal {

    @XmlElement(name = "Contenu", required = true)
    protected List<Contenu> contenu;
    @XmlElement(name = "Preambule", required = true)
    protected List<Preambule> preambule;

    /**
     * Gets the value of the contenu property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the contenu property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContenu().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Contenu }
     * 
     * 
     */
    public List<Contenu> getContenu() {
        if (contenu == null) {
            contenu = new ArrayList<Contenu>();
        }
        return this.contenu;
    }

    /**
     * Gets the value of the preambule property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the preambule property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPreambule().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Preambule }
     * 
     * 
     */
    public List<Preambule> getPreambule() {
        if (preambule == null) {
            preambule = new ArrayList<Preambule>();
        }
        return this.preambule;
    }

}
